language: objective-c
osx_image: xcode10
branches:
  only:
    - develop
    - master
env:
  global:
    - PROJECT="Scope.xcodeproj"
    - SCHEME="Scope"
    - IOS="iphonesimulator12.0"
    - MAXOS="macosx10.14"
    - TVOS="appletvsimulator12.0"
    - FRAMEWORK="Scope"
  matrix:
    - SDK="$IOS"    DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.0"
    - SDK="$MACOS"  DESTINATION="arch=x86_64"
    - SDK="$TVOS"   DESTINATION="OS=12.0,name=Apple TV 4K"

install:
  - swift --version

before_script:
  - set -o pipefail

script:
  - travis_retry xcodebuild clean build test
    -project "$PROJECT"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    ONLY_ACTIVE_ARCH=NO | xcpretty -c
