name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: [
            'platform=iOS Simulator,OS=12.2,name=iPhone XS',
            'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K'
        ]

    steps:
    - uses: actions/checkout@v1

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$project" \
          -scheme "$scheme" \
          -destination "$destination" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        project: Scope.xcodeproj
        scheme: Scope
        destination: ${{ matrix.destination }}
